Update gtk themes and switch to xfce

diff --git a/bin/mount_vault b/bin/mount_vault
--- a/bin/mount_vault
+++ b/bin/mount_vault
@@ -1,5 +1,15 @@
 #!/bin/sh
 
+if [ $(id -u) != 0 ]; then
+    echo "You must be root to run this script"
+    exit 1
+fi
+
+if [ $# != 1 ]; then
+    echo "An argument is required"
+    exit 1
+fi
+
 partition="$1"
 
 cryptsetup open $partition vault
